name: Java CI with Gradle
on: [push]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/poi/poi/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'basak'
    - run: touch starting_build_uses-checkout_14
    - run: rm starting_build_uses-checkout_14
    - uses: actions/checkout@v3
    - run: touch starting_build_SetupJDK_15
    - run: rm starting_build_SetupJDK_15
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        cache: gradle
    - run: touch starting_build_VerifyGradlewrapper_21
    - run: rm starting_build_VerifyGradlewrapper_21
    - name: Verify Gradle wrapper
      uses: gradle/wrapper-validation-action@v1
    - run: touch starting_build_Grantexecutepermissionforgradlew_23
    - run: rm starting_build_Grantexecutepermissionforgradlew_23
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - run: touch starting_build_BuildwithGradle_25
    - run: rm starting_build_BuildwithGradle_25
    - name: Build with Gradle
      run: ./gradlew check -PjdkVersion=11 --no-daemon --refresh-dependencies
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Pushes analysis to another repository
      if: always()
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'optimizing-ci-builds-ci-analysis'
        destination-github-username: 'UT-SE-Research'
        destination-repository-name: 'ci-analyzes'
        target-branch: '1675896667'
        target-directory: 'poi/.github/workflows/test-gradle/build'

